sudo: required

services:
  - docker

language: python

python:
  - 3.6

install: # replaced by docker image with conda

before_script:
  - docker build -t testenv .

env:
  - RUN="docker run -it testenv"

script:
  - $RUN mysql -h localhost -u travis <<<'SELECT 2+3;'
  - $RUN python3 -m unittest discover -s test -p "*_test.py"