sudo: required

services:
  - docker

cache:
  directories:
    - docker

language: python

python:
  - 3.6

install: # replaced by docker image with conda

before_script:
  - docker build -t my-test-qt .
  - docker run -it my-test-qt /bin/bash

script:
  - mysql -h localhost -u travis <<<'SELECT 2+3;'
  - python3 -m unittest discover -s test -p "*_test.py"