sudo: required

services:
  - docker
  - mysql

language: python

python:
  - 3.6

install: # replaced by docker image with conda

before_script:
  - docker build -t testenv .

env:
  - RUN="docker run testenv"

script:
  - docker run --net='host' testenv mysql -h localhost -u travis <<<'SELECT 2+3;'
  - docker run --net='host' testenv python3 -m unittest discover -s test -p '*_test.py'