sudo: required

services:
  - docker
  - mysql

language: python

python:
  - 3.6

before_script:
  - docker build -t my-test-qt .
  - docker run my-test-qt

script:
  - mysql -h localhost -u travis <<<'SELECT 2+3;'
  - python3 -m unittest discover -t /root -s /root/test -p "*_test.py"