sudo: required

services:
  - docker

cache:
  directories:
    - docker

language: python

python:
  - 3.6

install:
  - source activate testenv

before_script:
  - docker build -t my-test-qt .
  - docker run my-test-qt python3 -c "import pymysql"

script:
  - mysql -h localhost -u travis <<<'SELECT 2+3;'
  - python3 -m unittest discover -s test -p "*_test.py"