sudo: required

services:
  - docker

cache:
  directories:
    - docker

language: python

python:
  - 3.6

install:
  - conda env create --name test_env --file environment.yml
  - source activate test-env
  - python setup.py install

before_script:
  - docker build -t my-test-qt .
  - docker run my-test-qt
  - source activate test_env
  - python3 -c "import pymysql"

script:
  - mysql -h localhost -u travis <<<'SELECT 2+3;'
  - python3 -m unittest discover -s test -p "*_test.py"